### ISSUE TITLE
FEATURE: add sql to AlbumTable to insert new album

### ISSUE THREAD

**Issue by ecedmondson** [ecedmondson/pitchfork_copycat#16]
query code should live in AlbumTable

**Comment by ecedmondson** [comment]
I am going to do this one next.

**Comment by banghartOSU** [comment]
Hey Emily,  I can do this if it hasn’t been completed yet!

**Comment by ecedmondson** [comment]
Sorry TJ. My bad but I totally just saw this. PR #28 is for this. I haven't tested it yet though.

**Comment by ecedmondson** [comment]
This has been merged
