### ISSUE TITLE
FEATURE: ability to create new genre

### ISSUE THREAD

**Issue by ecedmondson** [ecedmondson/pitchfork_copycat#34]
I've put this off because I don't know where to put it. Having a page to create a genre (which would be one form field seems silly to me. I thought about putting it in the search bar on the main page...but that doesn't make sense. 

It might make sense to add it into the add_album/add_artist page, but that might require some JS callbacks. Not entirely sure. Might need to suck it up and make it's own page.

**Comment by banghartOSU** [comment]
I put in a PR for this on the artist page but it doesn't update the DOM quite yet. Simply reloads the page for now .

**Comment by ecedmondson** [comment]
As I have merged PR #38, I'm going to go ahead and close this. Thanks @banghartOSU !
