### ISSUE TITLE
FIX: adding new genre doesn't break if only one genre is added

### ISSUE THREAD

**Issue by ecedmondson** [ecedmondson/pitchfork_copycat#35]
I didn't realize this until after I submitted the PR, but the way I set up adding genres might cause the app to break if only one genre is added to an artist/album. 

This issue should:
1) check to see if that is indeed the case
2) if it is the case: modify the line in the _update_artist_genre and _update_album_genre functions in database/models/tables.py where the genre ids are put into a list. It looks something like this:
genres = [int(x) for x in genres.split(",")]
Might need to check length of the original genres. Not sure.

**Comment by ecedmondson** [comment]
I am working on this as part of testing the adding album sql PR

**Comment by ecedmondson** [comment]
This was actually working how it was already. I tested it as part of PR #28. I'm going to close this now.

**Comment by banghartOSU** [comment]
This works -- thanks!
